In [14]:
import torch
import numpy as np
import pandas as pd

In [36]:
data = np.load("./data/STRAD_2d.npy")
data.shape

(117498, 1, 7, 4)

In [35]:
# data = np.expand_dims(data,axis=1)
# np.save("./data/STRAD_2d.npy",data)

In [16]:
data = torch.from_numpy(data)
data.shape

torch.Size([117498, 7, 4])

In [18]:
df = pd.read_csv("./data/STRAD.csv")
df = df[df['Amount'] != 0]
df = df[df['Labels'] != 2]
labels = df['Labels'].to_numpy()
np.save("./data/STRAD_labels.npy", labels)

In [1]:
import importlib

In [2]:
import models

In [66]:
importlib.reload(models)
cnn = models.modelHandler()


c:\Users\bin\anaconda3\lib\site-packages\torch\nn\modules\lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [67]:
cnn.train()
# time window
# 类别embedding

weights info: tensor([0.6411, 2.2723])
label 1 ratio: 0.22004471023455852


100%|██████████| 173/173 [00:01<00:00, 97.02it/s] 


Epoch: 0, loss: 0.6937478332850285, acc: 0.22004471023455852
[[    0 68732]
 [    0 19391]]


100%|██████████| 173/173 [00:01<00:00, 101.09it/s]


Epoch: 1, loss: 0.6931220392960344, acc: 0.22754558968714184
[[  800 67932]
 [  139 19252]]


100%|██████████| 173/173 [00:01<00:00, 102.36it/s]


Epoch: 2, loss: 0.693010480073146, acc: 0.31814622743211196
[[11034 57698]
 [ 2389 17002]]


100%|██████████| 173/173 [00:01<00:00, 100.16it/s]


Epoch: 3, loss: 0.6929763173092307, acc: 0.4670630822827185
[[29112 39620]
 [ 7344 12047]]


100%|██████████| 173/173 [00:01<00:00, 99.89it/s] 


Epoch: 4, loss: 0.6929486776362954, acc: 0.4988141574844252
[[33052 35680]
 [ 8486 10905]]


100%|██████████| 173/173 [00:01<00:00, 96.77it/s] 


Epoch: 5, loss: 0.6929226507341242, acc: 0.5059178648026055
[[33936 34796]
 [ 8744 10647]]


100%|██████████| 173/173 [00:01<00:00, 101.81it/s]


Epoch: 6, loss: 0.6928971668199307, acc: 0.5048852172531575
[[33749 34983]
 [ 8648 10743]]


100%|██████████| 173/173 [00:01<00:00, 98.48it/s] 


Epoch: 7, loss: 0.6928712539590163, acc: 0.5033532675918886
[[33549 35183]
 [ 8583 10808]]


100%|██████████| 173/173 [00:01<00:00, 100.57it/s]


Epoch: 8, loss: 0.6928436046390865, acc: 0.4833357920179749
[[30946 37786]
 [ 7744 11647]]


100%|██████████| 173/173 [00:01<00:00, 97.60it/s] 


Epoch: 9, loss: 0.6928150502243483, acc: 0.4728731432202717
[[29617 39115]
 [ 7337 12054]]


100%|██████████| 173/173 [00:01<00:00, 98.28it/s] 


Epoch: 10, loss: 0.6927851214574251, acc: 0.46065158925592636
[[28025 40707]
 [ 6822 12569]]


100%|██████████| 173/173 [00:01<00:00, 100.47it/s]


Epoch: 11, loss: 0.6927547806260214, acc: 0.45405853182483574
[[27157 41575]
 [ 6535 12856]]


100%|██████████| 173/173 [00:01<00:00, 101.48it/s]


Epoch: 12, loss: 0.69272430198041, acc: 0.454183357352791
[[27181 41551]
 [ 6548 12843]]


100%|██████████| 173/173 [00:01<00:00, 97.88it/s] 


Epoch: 13, loss: 0.6926925754271491, acc: 0.45435357398182086
[[27196 41536]
 [ 6548 12843]]


100%|██████████| 173/173 [00:01<00:00, 94.83it/s]


Epoch: 14, loss: 0.692659371505583, acc: 0.45446705173450747
[[27221 41511]
 [ 6563 12828]]


100%|██████████| 173/173 [00:01<00:00, 97.77it/s] 


Epoch: 15, loss: 0.6926251219187168, acc: 0.4541379662517164
[[27176 41556]
 [ 6547 12844]]


100%|██████████| 173/173 [00:01<00:00, 99.53it/s] 


Epoch: 16, loss: 0.6925881890892294, acc: 0.45357057748828344
[[27087 41645]
 [ 6508 12883]]


100%|██████████| 173/173 [00:01<00:00, 97.60it/s]


Epoch: 17, loss: 0.6925454983821494, acc: 0.45282162432055195
[[26995 41737]
 [ 6482 12909]]


100%|██████████| 173/173 [00:01<00:00, 100.37it/s]


Epoch: 18, loss: 0.6924997037545794, acc: 0.45250388661302954
[[26944 41788]
 [ 6459 12932]]


100%|██████████| 173/173 [00:01<00:00, 94.57it/s] 


Epoch: 19, loss: 0.6924562209603414, acc: 0.4522655833323877
[[26915 41817]
 [ 6451 12940]]


100%|██████████| 173/173 [00:01<00:00, 97.19it/s] 


Epoch: 20, loss: 0.692414520448343, acc: 0.4517095423442234
[[26836 41896]
 [ 6421 12970]]


100%|██████████| 173/173 [00:01<00:00, 98.53it/s] 


Epoch: 21, loss: 0.6923711661658535, acc: 0.45143719573777563
[[26804 41928]
 [ 6413 12978]]


100%|██████████| 173/173 [00:01<00:00, 100.77it/s]


Epoch: 22, loss: 0.6923252984967535, acc: 0.4514145001872383
[[26793 41939]
 [ 6404 12987]]


100%|██████████| 173/173 [00:01<00:00, 99.11it/s] 


Epoch: 23, loss: 0.6922774383787474, acc: 0.4498144638743574
[[26593 42139]
 [ 6345 13046]]


100%|██████████| 173/173 [00:01<00:00, 102.99it/s]


Epoch: 24, loss: 0.6922279365489937, acc: 0.4495761605937156
[[26569 42163]
 [ 6342 13049]]


100%|██████████| 173/173 [00:01<00:00, 99.11it/s] 


Epoch: 25, loss: 0.6921767358145962, acc: 0.448997424055014
[[26490 42242]
 [ 6314 13077]]


100%|██████████| 173/173 [00:01<00:00, 98.64it/s] 


Epoch: 26, loss: 0.6921249676301989, acc: 0.44774916877546156
[[26288 42444]
 [ 6222 13169]]


100%|██████████| 173/173 [00:01<00:00, 98.80it/s] 


Epoch: 27, loss: 0.6920713541135622, acc: 0.44648956572064047
[[26120 42612]
 [ 6165 13226]]


100%|██████████| 173/173 [00:01<00:00, 102.64it/s]


Epoch: 28, loss: 0.6920158256685114, acc: 0.44510513713786415
[[25926 42806]
 [ 6093 13298]]


100%|██████████| 173/173 [00:01<00:00, 102.88it/s]

Epoch: 29, loss: 0.691958933207341, acc: 0.443811490757237
[[25743 42989]
 [ 6024 13367]]
